### ISSUE TITLE
Residual Firewall settings

### ISSUE THREAD

**Issue by MalakaiJKB** [DrNoLife/Destiny-2-Solo-Enabler#10]
Love the app, appreciate your putting it together. It has definitely helped me out.

The only issue I have with it is once you disable to enabler, there are some setting still left in place in the firewall. With it disabled, It still takes a very long time to connect to servers and bring up character select. It will also sometimes timeout when trying to load Destiny 2 upon launching. If I go into the Windows Firewall, and reset to default, the game will launch and connect to servers almost immediately.

**Comment by ashicus** [comment]
With solo play disabled, open a PowerShell and type:  `get-netfirewallrule -all`

Do you see any rules where the `DisplayName` is "Destiny 2 - Solo-Enabler"?

**Comment by MalakaiJKB** [comment]
I actually hadn't parsed the firewall rules to investigate the issue, I
resolved the issue by just resetting all firewall rules to default. I am
going to be using it to grind out some stuff in the game, so I can take a
deeper look after following your above steps. I can let you know what I
find.

Justin

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Telogor** [comment]
I can confirm that the latest release is not correctly removing the firewall rules, and attempting to delete them manually via cmd/powershell results in a 0x2 error.  I had to reset my firewall to default.

Windows version 19042.844

**Comment by DrNoLife** [comment]
And how are you confirming that? Because when _I_ check out the rules (by opening up 'Windows Defender Firewall with Advanced Security') there are no rules related to the program when it's turned off. As soon as I turn it on, the rules appear, but they disappear as soon as I shut it off again - the intended behaviour.

Also your error, 0x2 seems to be about "scheduled tasks" or using the task scheduler. Nothing in the program makes it so you cannot remove the rules. Also also, if you actually want to remove them manually, open up the GUI for your firewall, by using 'Windows Defender Firewall with Advanced Security'.

**Comment by Telogor** [comment]
You know, it's not good dev practice to dismiss bug reports like that.

I opened up the list of firewall rules in "Windows Defender Firewall with Advanced Security" with your application turned off, and there were several firewall rules still active.  I was unable to remove them via command prompt/Powershell with the normal command, and there was no way to remove them from the Windows Defender Firewall UI.  Thus, I was forced to reset my firewall rules to be rid of your application's leftovers.

Perhaps try bug testing.  Perhaps try recreating the issue I found.  I even gave you my OS build number, so you can check to see whether it's an issue with Windows or your app.

**Comment by DrNoLife** [comment]
Where did I dismiss it? I asked you _how_ you were confirming it. Why would I do that? Because I've experienced countless of people saying the program isn't working, just to spend time helping them out, all so I find out they are using third party firewalls. I have no intention in wasting a lot of time, trying to help, before actually knowing there exists a problem.

Based on the experiences of many hundreds of other people, the only logical explenation is that something on your end is acting up. I can recommend that you try to downgrade your WIndows install version to a working one (the one I'm currently using is 19042.804). You could even try another solution and see if that fits your needs somewhat better (there are numerous PowerShell scripts which does what this program does), here are a few:

- [Enabling Solo Mode for Destiny 2 [Working w/ Season of Chosen]](https://steamcommunity.com/sharedfiles/filedetails/?id=1948325295)
- [[Software] Destiny 2 PC - Solo Mode](https://www.reddit.com/r/DestinyTheGame/comments/ejll0q/software_destiny_2_pc_solo_mode/)

Let me know if any of those are working as intended. 

Also remember. Use only the Windows Firewall, no others. That means no Avast or Norton. There have been reports of having to uninstall those programs, even if only using them for their anti-virus function. This (I'm guessing) is due to the way they function internally.

**Comment by Telogor** [comment]
I was able to locate the issue for my particular setup.  Smite had not exited correctly and still had some active processes, and I suspect its EasyAntiCheat was interfering with this application's ability to change firewall settings.
