### ISSUE TITLE
Can't play with matchmaking anymore

### ISSUE THREAD

**Issue by hersek138** [DrNoLife/Destiny-2-Solo-Enabler#14]
I have been using this program for the past couple weeks with no issues besides the crashing issue that another user posted below. But as of today when I used the .exe I can no longer play with matchmaking. It is like I never turned it off but I most definitely did. I have restarted the game and program multiple times but to no avail. I am not very good with computers so I am at a loss as to what to do to fix it. Can someone please help me?

**Comment by DrNoLife** [comment]
Check your firewall, see if you have the rules added, if you have, then delete them.

In your Windows search bar, search for "Firewall" and select "Windows Defender Firewall with Advanced Security".
From there, first go into Inbound rules and look for the name "Destiny 2 - Solo-Enabler". If you find any rules in there, then right click on them, and delete them.
Afterwards, do the same thing in "Outbound rules".

**Comment by nyxnik** [comment]
I have the same problem and there's no freaking solution it seems dude what the actual hell. The rules are in "monitoring" for some reason instead of being where they should and I can't delete them neither directly nor through the CMD...
![Screenshot_2](https://user-images.githubusercontent.com/77552995/142480531-4d945467-b946-4a60-b4dc-3711f0776bd9.png)
![Screenshot_1](https://user-images.githubusercontent.com/77552995/142480535-05cccec8-245a-475d-a3fa-fa3f0ee51da0.png)

**Comment by nyxnik** [comment]
> I have the same problem and there's no freaking solution it seems dude what the actual hell. The rules are in "monitoring" for some reason instead of being where they should and I can't delete them neither directly nor through the CMD... ![Screenshot_2](https://user-images.githubusercontent.com/77552995/142480531-4d945467-b946-4a60-b4dc-3711f0776bd9.png) ![Screenshot_1](https://user-images.githubusercontent.com/77552995/142480535-05cccec8-245a-475d-a3fa-fa3f0ee51da0.png)

Ok I solved my problem, it seems that for some reason the app bugged out or something. In case it happens to anyone else, you'll most likely need to reset the firewall settings (from the Advanced Settings tab, top left -> Restore Default Policy).
