### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by BSingels** [DrNoLife/Destiny-2-Solo-Enabler#31]
Hi there DrNoLife,

I'd like to make a request. Ia it possible to assign a shortcut key sequence to to program. 
It would make it a lot easier for me to use, I'd even be willing to pay for it if that helps.

My apologies for posting it here I could not figure out where else to do it.

Thank you for your awesome tool. I use it all the time!! 

Best Regards,
Bert Singels

**Comment by DrNoLife** [comment]
I'll give it a look whenever I get the time. The combination of school + work keeps me quite busy. 
But just know, I've seen your request, and I'll give an update when I figure something out.

**Comment by BSingels** [comment]
Hi there DrNoLife,

I am just very grateful that you are willing to look at it at all.
Life can very busy, think of your physical and mental health, I'll be waiting patiently.

Best Regards,
Bert Singels

P.s . Do you take any kind of donations, not to speed anything up but just as a general thank you for all the work you already put in.

**Comment by DrNoLife** [comment]
Update @BSingels.

I added basic hotkey functionality to the program, you can get the latest release here 
https://github.com/DrNoLife/Destiny-2-Solo-Enabler/releases/tag/2.5 

There are a few downsides. 

- The hotkey is a static one, meaning the user can't change it.
- Due to including nuget packages, the program is dependent on an external library, meaning I can't make the release a singular .exe file anymore (this will most likely be changed in the future. There are two ways of changing it: 1) Write the hotkey code myself or 2) Update the program to .NET Core from .NET Framework).

Anyhow, let me know if you encounter any bugs or weird behaviour. Once again thanks for the suggestion 😄 

Ps. I don't have any form of donation link set up right now. I might in the future but haven't given it much thought before.

Pps. Sorry that it took so long and that the current version is not optimal. It'll be improved in the future!

**Comment by BSingels** [comment]
Hi there DrNoLife,

You are phenomenal. I am very happy with this.  Thank you!!! 
I will let you know if I encounter any problems. 

Good luck on your final exam and again thank you!
