### ISSUE TITLE
Asking For Clarification

### ISSUE THREAD

**Issue by KawaiiScorpy** [DrNoLife/Destiny-2-Solo-Enabler#33]
Hello DrNoLife

Bungie has banned a lot of accounts recently without reason. Most people said that Bungie banned them because they are using net limiter. I'm just wondering if destiny solo enabler will be counted as a net limiter or not. I was worrying and I hope you can clarify this problem. Thank you 

Best Regards

**Comment by BLTplayz** [comment]
Honestly, I do not believe there is any risk in using this. This program simply makes your PC block matchmaking by blocking its network port. It does not actually modify the connection to game servers (I believe). 

Of course, use it at your own risk! But I've been fine for a while now :)

**Comment by DrNoLife** [comment]
What @BLTplayz said is correct. It does not modify the transfer of data between client and server. What it does, is completely block out your client's possibility of communicating with Steam's service that handles match making. This same situation could also happen if one had a really terrible internet connection. Or an incorrectly setup firewall. Thus, I'd wager and say, that the possibility of Bungie slamming down on this, is minimal to none.

So far, there has not been a single reported incident where someone has been banned due to using this program.
