### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Aptronymist** [DrNoLife/Destiny-2-Solo-Enabler#38]
I use this almost every day for running solo vanguards to blow through multiple vendor bounties in a short period of time, so let me start by thanking you for making and maintaining this!

My request would be an exclusion list. I'm not sure if this would work, but it seems likely that it would, but the idea is to allow people to add ip addresses to a list, and those would be excluded from the filtering on the relevant ports.

This way you could do a larger than one non-matchmade fireteam if every member was allowing traffic from the other players in the fireteam. For example, a 2 man vanguard with no randos shoved in that might spoil whatever farming or whatnot you would be trying to do.

Thanks again!

**Comment by DrNoLife** [comment]
Unfortunately, the program does not work by blocking IP'addresses (or allowing certain others).

What Destiny 2 does, is use a Steam service for handling it's matchmaking. This Steam service uses a certain range of ports, and by blocking all traffic to these ports, you can circumvent the matchmaking, and get into an instance of your own. This works, because the game can't tell a difference between you having blocked the ports, or you just having trouble with your internet connection.

**Comment by Aptronymist** [comment]
Ohhh, my bad. I misunderstood, I didn't know steam was involved in it as a middleman. 
Thank you for the reply at least!
